// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz2gd-Z2faL6pO6HvkO571sRc7XKtOVOM',
    appId: '1:467855322828:web:b12b9f6105bffc136fdc69',
    messagingSenderId: '467855322828',
    projectId: 'appppublica',
    authDomain: 'appppublica.firebaseapp.com',
    storageBucket: 'appppublica.firebasestorage.app',
    measurementId: 'G-V5VLB09194',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUQ8UaIDlNg3S-dCAxSJOPkLss0WJp3NQ',
    appId: '1:467855322828:android:b4df2a45302322926fdc69',
    messagingSenderId: '467855322828',
    projectId: 'appppublica',
    storageBucket: 'appppublica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowBj7gkbDXAqrjxHWKiClTN6nIaoIypw',
    appId: '1:467855322828:ios:d245e9d1183d8a616fdc69',
    messagingSenderId: '467855322828',
    projectId: 'appppublica',
    storageBucket: 'appppublica.firebasestorage.app',
    iosBundleId: 'com.example.appPPublica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCowBj7gkbDXAqrjxHWKiClTN6nIaoIypw',
    appId: '1:467855322828:ios:d245e9d1183d8a616fdc69',
    messagingSenderId: '467855322828',
    projectId: 'appppublica',
    storageBucket: 'appppublica.firebasestorage.app',
    iosBundleId: 'com.example.appPPublica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz2gd-Z2faL6pO6HvkO571sRc7XKtOVOM',
    appId: '1:467855322828:web:280edc56220583056fdc69',
    messagingSenderId: '467855322828',
    projectId: 'appppublica',
    authDomain: 'appppublica.firebaseapp.com',
    storageBucket: 'appppublica.firebasestorage.app',
    measurementId: 'G-V365WVTLX9',
  );
}
